"""
Documento base da farmácia — princípios ativos (a espinha dorsal do estoque de
medicamentos, hormônios e vacinas) e suas marcas comerciais/laboratórios.

Cada entrada define a molécula (ou, para biológicos, o antígeno/doença), a
unidade-base em que o saldo das apresentações é somado (unificação de volumes) e
a apresentação primária cujo mínimo padrão é 1 (1 frasco/pote/seringa/dose).

O seed é idempotente (guardado por SeedFlag em main.py) e só CRIA o que falta —
nunca sobrescreve edições do usuário nem apaga histórico.
"""
from __future__ import annotations

# unidade_base: unidade canônica do somatório do princípio (ml | L | dose | unidade)
# unidade_apresentacao: recipiente primário cujo mínimo padrão é 1
PRINCIPIOS: list[dict] = [
    # ── Antimicrobianos e Antibióticos ──────────────────────────────────────
    {"nome": "Penicilina G (Procaína, Potássica e Benzatina)", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Sistêmico Injetável",
     "uso_principal": "Infecções sistêmicas, clostridioses, pneumonia, mastites severas.",
     "justificativa": "Controle em frascos (ml). Primeira linha de defesa.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Pentabiótico Veterinário", "Zoetis"), ("Agropen", "Agener União"), ("Pencivet Plus", "MSD"), ("Penfort", "Ourofino"), ("Agrovet", "Elanco")]},
    {"nome": "Ceftiofur", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Sistêmico Injetável",
     "uso_principal": "DRB, infecções podais, metrites. Carência zero para leite em injetáveis específicos.",
     "justificativa": "Controle em frascos (ml). Alta prioridade estratégica.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Excenel", "Zoetis"), ("Lactofur", "Ourofino"), ("Ceftiofur 50", "Ourofino"), ("Ubrolexin", "Boehringer Ingelheim"), ("Ready Free", "Agener União")]},
    {"nome": "Oxitetraciclina (LA)", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Sistêmico Injetável",
     "uso_principal": "Anaplasmose, infecções podais.",
     "justificativa": "Controle em frascos (ml). Base para suporte de febre/carrapatos.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Terramicina LA", "Zoetis"), ("Ourotetracina LA", "Ourofino"), ("Revemycina", "Virbac"), ("Biociclin LA", "Biovet")]},
    {"nome": "Florfenicol", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Sistêmico Injetável",
     "uso_principal": "Doenças respiratórias agudas.",
     "justificativa": "Controle em frascos (ml). Bloquear uso na lactação.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Roflin", "Ourofino"), ("Nuflor", "MSD"), ("Maxflor", "Elanco"), ("Selectan", "Hipra")]},
    {"nome": "Sulfadoxina + Trimetoprima", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Sistêmico Injetável",
     "uso_principal": "Diarreias, pneumonias, cascos.",
     "justificativa": "Controle em frascos (ml). Foco em bezerros e suporte rápido.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Borgal", "Virbac"), ("Trissulfin Injetável", "Ourofino"), ("Doxifin", "Ourofino"), ("Gorban", "MSD")]},
    {"nome": "Enrofloxacina", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Sistêmico Injetável",
     "uso_principal": "Infecções geniturinárias graves, infecção de umbigo.",
     "justificativa": "Controle em frascos (ml). Descarte rigoroso de leite.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Flotril", "MSD"), ("Enrofloxacina 10%", "Ourofino"), ("Kinetomax", "Elanco"), ("Chemitril", "Chemitec")]},
    {"nome": "Cefalônio", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Intramamário (Vaca Seca)",
     "uso_principal": "Terapia preventiva para período seco.",
     "justificativa": "Controle em seringas (unidade). Vinculado às datas de secagem.",
     "unidade_base": "unidade", "unidade_apresentacao": "seringa",
     "marcas": [("Cepravin Vaca Seca", "MSD")]},
    {"nome": "Cefoperazona", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Intramamário (Lactação)",
     "uso_principal": "Mastite clínica na ordenha.",
     "justificativa": "Controle em seringas (unidade).",
     "unidade_base": "unidade", "unidade_apresentacao": "seringa",
     "marcas": [("Pathozone", "Zoetis"), ("Mastitrat", "Ourofino")]},
    {"nome": "Gentamicina", "categoria": "Antimicrobianos e Antibióticos", "categoria_software": "Antimicrobiano Intramamário (Lactação)",
     "uso_principal": "Mastite coliforme aguda.",
     "justificativa": "Controle em seringas (unidade).",
     "unidade_base": "unidade", "unidade_apresentacao": "seringa",
     "marcas": [("Gentocin Mastite", "MSD"), ("Mastite Clínica", "Ourofino")]},
    # ── Anti-inflamatórios e Analgésicos ────────────────────────────────────
    {"nome": "Flunixina Meglumina", "categoria": "Anti-inflamatórios e Analgésicos", "categoria_software": "AINE",
     "uso_principal": "Dores viscerais crônicas, choque endotóxico.",
     "justificativa": "Controle em frascos (ml). Emergência de curral.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Banamine", "MSD"), ("Flunamine", "Ourofino"), ("Desflan", "Ourofino")]},
    {"nome": "Meloxicam", "categoria": "Anti-inflamatórios e Analgésicos", "categoria_software": "AINE",
     "uso_principal": "Distúrbios locomotores, mastite, analgesia prolongada.",
     "justificativa": "Controle em frascos (ml). Tratamento primário.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Maxicam 2%", "Ourofino"), ("Aliv V", "Bimeda"), ("Meloxifin", "Ourofino"), ("Metacam", "Boehringer Ingelheim")]},
    {"nome": "Cetoprofeno", "categoria": "Anti-inflamatórios e Analgésicos", "categoria_software": "AINE",
     "uso_principal": "Edema de úbere, febre.",
     "justificativa": "Controle em frascos (ml). Carência zero para leite predominante.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Ketofen 10%", "Ceva"), ("Ketoflex", "Ourofino"), ("Ketofarm", "Ourofino")]},
    {"nome": "Dexametasona", "categoria": "Anti-inflamatórios e Analgésicos", "categoria_software": "Corticoide",
     "uso_principal": "Choque, cetose, alergia.",
     "justificativa": "Controle em frascos (ml). Alerta de risco de aborto em fêmeas prenhes.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Azium", "MSD"), ("Cortiflan", "Ourofino"), ("Dexaflex", "Ourofino")]},
    {"nome": "Dipirona Sódica", "categoria": "Anti-inflamatórios e Analgésicos", "categoria_software": "Analgésico/Antipirético",
     "uso_principal": "Febres sintomáticas, cólicas leves.",
     "justificativa": "Controle em frascos (ml). Alta rotatividade.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("D-500", "Zoetis"), ("Finador", "Ourofino")]},
    # ── Fármacos Reprodutivos e Hormônios ───────────────────────────────────
    {"nome": "Cloprostenol Sódico / D-Cloprostenol", "categoria": "Fármacos Reprodutivos e Hormônios", "categoria_software": "Hormônio Luteolítico",
     "uso_principal": "Sincronização (IATF), lise de corpo lúteo, indução de parto.",
     "justificativa": "Controle em frascos (ml). Calculado via agenda reprodutiva.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Ciosin", "MSD"), ("Sincrocio", "Ourofino"), ("Estrumate", "MSD"), ("Prolise", "Tecnopec")]},
    {"nome": "Benzoato de Estradiol", "categoria": "Fármacos Reprodutivos e Hormônios", "categoria_software": "Hormônio Estrogênico",
     "uso_principal": "Sincronização de onda folicular (D0 IATF).",
     "justificativa": "Controle em frascos (ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Sincrodiol", "Ourofino"), ("Gonadiol", "Zoetis"), ("Estrogin", "Agener")]},
    {"nome": "Cipionato de Estradiol", "categoria": "Fármacos Reprodutivos e Hormônios", "categoria_software": "Hormônio Estrogênico",
     "uso_principal": "Indutor de ovulação final (IATF).",
     "justificativa": "Controle em frascos (ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("E.C.P.", "Zoetis"), ("SincroCP", "Ourofino")]},
    {"nome": "Progesterona", "categoria": "Fármacos Reprodutivos e Hormônios", "categoria_software": "Hormônio Progestágeno",
     "uso_principal": "Implantes intravaginais para IATF.",
     "justificativa": "Controle em unidades/dispositivos.",
     "unidade_base": "unidade", "unidade_apresentacao": "dispositivo",
     "marcas": [("CIDR", "Zoetis"), ("Sincrogest", "Ourofino"), ("DIB", "Zoetis/König")]},
    {"nome": "Gonadotrofina Coriônica Equina (eCG)", "categoria": "Fármacos Reprodutivos e Hormônios", "categoria_software": "Hormônio Estimulante Folicular",
     "uso_principal": "Estímulo ovariano em vacas em anestro.",
     "justificativa": "Controle em frascos/doses.",
     "unidade_base": "dose", "unidade_apresentacao": "frasco",
     "marcas": [("Novormon", "Zoetis"), ("SincroeCG", "Ourofino"), ("Folligon", "MSD")]},
    {"nome": "Ocitocina", "categoria": "Fármacos Reprodutivos e Hormônios", "categoria_software": "Hormônio Ocitócico",
     "uso_principal": "Retenção de placenta, auxílio descida de leite.",
     "justificativa": "Controle em frascos (ml). Maternidade e ordenha.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Ocitocina Forte UCB", "Ucbvet"), ("Placentina", "Ucbvet"), ("Orastina", "Bayer")]},
    {"nome": "Buserelina", "categoria": "Fármacos Reprodutivos e Hormônios", "categoria_software": "Hormônio GnRH",
     "uso_principal": "Cistos ovarianos, forçar ovulação.",
     "justificativa": "Controle em frascos (ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Cystorelin", "Boehringer Ingelheim"), ("Sincrorelin", "Ourofino"), ("Conceptase", "Agener")]},
    # ── Antiparasitários ────────────────────────────────────────────────────
    {"nome": "Ivermectina", "categoria": "Antiparasitários (Ecto, Endo e Hemoparasiticidas)", "categoria_software": "Endectocida Injetável",
     "uso_principal": "Nematódeos e carrapatos.",
     "justificativa": "Controle em frascos (ml). Bloquear uso na lactação. Foco recria.",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Ivomec Injetável", "Boehringer Ingelheim"), ("Ivermina", "Ourofino"), ("Master LP", "Ourofino")]},
    {"nome": "Doramectina", "categoria": "Antiparasitários (Ecto, Endo e Hemoparasiticidas)", "categoria_software": "Endectocida Injetável",
     "uso_principal": "Parasitas, miíases (bicheira/umbigo).",
     "justificativa": "Controle em frascos (ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Dectomax", "Zoetis"), ("Doramec", "Ourofino")]},
    {"nome": "Fluazuron", "categoria": "Antiparasitários (Ecto, Endo e Hemoparasiticidas)", "categoria_software": "Ectoparasiticida (Pour-on)",
     "uso_principal": "Quebra ciclo do carrapato (inibidor quitina).",
     "justificativa": "Controle em galões (litros).",
     "unidade_base": "L", "unidade_apresentacao": "galão",
     "marcas": [("Acatak", "Elanco"), ("Tickless", "Ourofino"), ("Ouroatac", "Ourofino")]},
    {"nome": "Fipronil", "categoria": "Antiparasitários (Ecto, Endo e Hemoparasiticidas)", "categoria_software": "Ectoparasiticida (Pour-on)",
     "uso_principal": "Mosca de chifre e carrapatos.",
     "justificativa": "Controle em galões (litros).",
     "unidade_base": "L", "unidade_apresentacao": "galão",
     "marcas": [("Topline", "Boehringer Ingelheim"), ("Fiprotack", "Ourofino")]},
    {"nome": "Amitraz", "categoria": "Antiparasitários (Ecto, Endo e Hemoparasiticidas)", "categoria_software": "Ectoparasiticida (Pulverização)",
     "uso_principal": "Banho aspersão choque carrapatos.",
     "justificativa": "Controle em frascos (litros).",
     "unidade_base": "L", "unidade_apresentacao": "frasco",
     "marcas": [("Triatox", "MSD"), ("Amitraz 12,5%", "Ourofino")]},
    {"nome": "Imidocarb", "categoria": "Antiparasitários (Ecto, Endo e Hemoparasiticidas)", "categoria_software": "Hemoparasiticida",
     "uso_principal": "Tratamento Tristeza Parasitária (Babesiose/Anaplasmose).",
     "justificativa": "Controle em frascos (ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Imizol", "MSD"), ("Izoot", "Ourofino")]},
    {"nome": "Albendazol", "categoria": "Antiparasitários (Ecto, Endo e Hemoparasiticidas)", "categoria_software": "Endoparasiticida Oral",
     "uso_principal": "Vermes intestinais/pulmonares.",
     "justificativa": "Controle em frascos (litros).",
     "unidade_base": "L", "unidade_apresentacao": "frasco",
     "marcas": [("Valbazen", "Zoetis"), ("Ricobendazol", "Ourofino"), ("Biozen", "Biovet")]},
    # ── Metabólicos, Vitaminas e Minerais ───────────────────────────────────
    {"nome": "Borogluconato de Cálcio", "categoria": "Metabólicos, Vitaminas e Minerais", "categoria_software": "Metabólico Injetável",
     "uso_principal": "Febre do leite, paralisia pós-parto.",
     "justificativa": "Controle em frascos (200-500ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Calfon", "Elanco"), ("Cálcio Farmative", "Ourofino"), ("Fortemil", "Ourofino")]},
    {"nome": "Toldimfós Sódico", "categoria": "Metabólicos, Vitaminas e Minerais", "categoria_software": "Estimulante Metabólico",
     "uso_principal": "Fornecimento de fósforo, estimulante.",
     "justificativa": "Controle em frascos (ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Catosal B12", "Elanco"), ("Fosfosan", "Virbac"), ("Ourofós", "Ourofino")]},
    {"nome": "Vitamina A + D3 + E", "categoria": "Metabólicos, Vitaminas e Minerais", "categoria_software": "Vitamina Injetável",
     "uso_principal": "Suporte nutricional, imunológico pré-parto.",
     "justificativa": "Controle em frascos (ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("ADE", "Ourofino"), ("Monovin A", "Bravet"), ("Adeforte", "Ucbvet")]},
    {"nome": "Cianocobalamina (B12)", "categoria": "Metabólicos, Vitaminas e Minerais", "categoria_software": "Vitamina Injetável",
     "uso_principal": "Estímulo energético.",
     "justificativa": "Controle em frascos (ml).",
     "unidade_base": "ml", "unidade_apresentacao": "frasco",
     "marcas": [("Dexacito", "Bravet"), ("Rubra 12", "Zoetis"), ("B12", "Ourofino")]},
    {"nome": "Propilenoglicol", "categoria": "Metabólicos, Vitaminas e Minerais", "categoria_software": "Suplemento Energético Oral",
     "uso_principal": "Tratamento de cetose.",
     "justificativa": "Controle em galões (litros).",
     "unidade_base": "L", "unidade_apresentacao": "galão",
     "marcas": [("Cetol", "Bravet"), ("Energet", "Agener"), ("Propilenoglicol", None)]},
    # ── Biológicos (Vacinas e Diagnósticos) — agrupados por doença/antígeno ──
    {"nome": "Brucelose Bovina (Cepa 19 ou RB51)", "categoria": "Biológicos (Vacinas e Diagnósticos)", "categoria_software": "Biológico (Vacina Liofilizada)",
     "justificativa": "Controle em doses. Requer trava sistêmica com receituário.",
     "unidade_base": "dose", "unidade_apresentacao": "dose", "eh_biologico": True, "doenca": "Brucelose",
     "marcas": [("RB51", "Zoetis"), ("Cepa 19", "Ourofino/Vencofarma")]},
    {"nome": "Clostridioses (Toxoides)", "categoria": "Biológicos (Vacinas e Diagnósticos)", "categoria_software": "Biológico (Vacina Bacterina)",
     "justificativa": "Controle em doses.",
     "unidade_base": "dose", "unidade_apresentacao": "dose", "eh_biologico": True, "doenca": "Clostridiose",
     "marcas": [("Poli-Star", "Ourofino"), ("Covexin 9", "Zoetis"), ("Fortress", "Zoetis")]},
    {"nome": "Reprodutiva (IBR, BVD, Leptospirose)", "categoria": "Biológicos (Vacinas e Diagnósticos)", "categoria_software": "Biológico (Vacina Reprodutiva)",
     "justificativa": "Controle em doses.",
     "unidade_base": "dose", "unidade_apresentacao": "dose", "eh_biologico": True, "doenca": "Leptospirose",
     "marcas": [("Supina", "Ourofino"), ("CattleMaster", "Zoetis"), ("Bioabortogen", "Biovet")]},
    {"nome": "Pré-parto Neonatal (Rotavírus, Coronavírus, E. coli)", "categoria": "Biológicos (Vacinas e Diagnósticos)", "categoria_software": "Biológico (Vacina Pré-parto)",
     "justificativa": "Controle em doses.",
     "unidade_base": "dose", "unidade_apresentacao": "dose", "eh_biologico": True, "doenca": "Diarreia Neonatal",
     "marcas": [("ScourGuard 4KC", "Zoetis"), ("Rotatec", "Elanco"), ("Lactovac", "Hipra")]},
    {"nome": "Pasteurelose e Paratifo dos Bezerros (Tifo-Pasteurina)", "categoria": "Biológicos (Vacinas e Diagnósticos)", "categoria_software": "Biológico (Vacina Pré-parto)",
     "justificativa": "Controle em doses. Aplicada por volta do 8º mês de gestação (30 dias antes do parto).",
     "uso_principal": "Imunidade passiva do bezerro contra pasteurelose e paratifo (Salmonella dublin/typhimurium, Pasteurella multocida) via colostro.",
     "unidade_base": "dose", "unidade_apresentacao": "dose", "eh_biologico": True, "doenca": "Pasteurelose e Paratifo dos Bezerros",
     "marcas": [("Tifopasteurina", "Hertape Calier")]},
    {"nome": "Tuberculina PPD Bovino", "categoria": "Biológicos (Vacinas e Diagnósticos)", "categoria_software": "Biológico (Diagnóstico)",
     "justificativa": "Controle em doses. Uso restrito para exames.",
     "unidade_base": "dose", "unidade_apresentacao": "dose", "eh_biologico": True, "doenca": "Tuberculose",
     "marcas": [("PPD Bovino", "Instituto Biológico / Ourofino")]},
]
