"""dia_inicial em protocolo sanitario

Revision ID: 00c885d4b5bd
Revises: 3c7a789316d3
Create Date: 2026-07-20 04:07:41.173192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c885d4b5bd'
down_revision: Union[str, Sequence[str], None] = '3c7a789316d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Padronização em D0 (jul/2026): protocolos sanitários passam a suportar
    # dia_inicial (0 ou 1), mesmo campo que já existe em
    # ProtocoloInducaoLactacao. server_default='1' é necessário porque a
    # tabela protocolo_sanitario já tem linhas em produção — SQLite não
    # permite ADD COLUMN NOT NULL sem um default quando a tabela não está
    # vazia — e o valor 1 preserva 100% o comportamento/datas atuais dos
    # protocolos já cadastrados (a fórmula de cálculo passa a ser
    # `dia - dia_inicial`, que com dia_inicial=1 é idêntica ao antigo `dia -
    # 1` hardcoded). O UPDATE abaixo é redundante com o server_default (já
    # preenche as linhas existentes), mas deixa explícito o backfill. Linhas
    # criadas depois desta migração usam o default do modelo Python
    # (dia_inicial=0), não este server_default.
    op.add_column('protocolo_sanitario', sa.Column('dia_inicial', sa.Integer(), nullable=False, server_default='1'))
    op.execute("UPDATE protocolo_sanitario SET dia_inicial = 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocolo_sanitario', 'dia_inicial')
    # ### end Alembic commands ###
