"""ferias e decimo terceiro

Revision ID: 03ae0a19ef2b
Revises: b38274335d19
Create Date: 2026-07-19 22:37:14.801029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03ae0a19ef2b'
down_revision: Union[str, Sequence[str], None] = 'b38274335d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decimo_terceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('parcela', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meses_trabalhados', sa.Integer(), nullable=False),
    sa.Column('valor_bruto', sa.Float(), nullable=False),
    sa.Column('valor_inss', sa.Float(), nullable=False),
    sa.Column('valor_ir', sa.Float(), nullable=False),
    sa.Column('valor_liquido', sa.Float(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('numero_lancamento_gerado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('centro_custo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ferias_funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('periodo_aquisitivo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_aquisitivo_fim', sa.Date(), nullable=False),
    sa.Column('dias_direito', sa.Integer(), nullable=False),
    sa.Column('dias_gozados', sa.Integer(), nullable=False),
    sa.Column('data_inicio_gozo', sa.Date(), nullable=False),
    sa.Column('data_fim_gozo', sa.Date(), nullable=False),
    sa.Column('abono_pecuniario_dias', sa.Integer(), nullable=False),
    sa.Column('valor_ferias', sa.Float(), nullable=False),
    sa.Column('valor_terco_constitucional', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('numero_lancamento_gerado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('centro_custo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ferias_funcionario')
    op.drop_table('decimo_terceiro')
    # ### end Alembic commands ###
