"""fgts e dctf na folha de pagamento

Revision ID: 52cb397abb88
Revises: 03ae0a19ef2b
Create Date: 2026-07-20 00:08:32.717586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cb397abb88'
down_revision: Union[str, Sequence[str], None] = '03ae0a19ef2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folha_pagamento', sa.Column('percentual_fgts', sa.Float(), nullable=True))
    op.add_column('folha_pagamento', sa.Column('valor_fgts', sa.Float(), nullable=True))
    op.add_column('folha_pagamento', sa.Column('percentual_dctf', sa.Float(), nullable=True))
    op.add_column('folha_pagamento', sa.Column('valor_dctf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folha_pagamento', 'valor_dctf')
    op.drop_column('folha_pagamento', 'percentual_dctf')
    op.drop_column('folha_pagamento', 'valor_fgts')
    op.drop_column('folha_pagamento', 'percentual_fgts')
    # ### end Alembic commands ###
