"""manutencao preventiva de patrimonio

Revision ID: 6b87f4f6ae02
Revises: 52cb397abb88
Create Date: 2026-07-20 03:06:17.971254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b87f4f6ae02'
down_revision: Union[str, Sequence[str], None] = '52cb397abb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manutencao_patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio_id', sa.Integer(), nullable=False),
    sa.Column('data_realizacao', sa.Date(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fornecedor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('centro_custo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('numero_lancamento_gerado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['patrimonio_id'], ['patrimonio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencao_patrimonio_patrimonio_id'), 'manutencao_patrimonio', ['patrimonio_id'], unique=False)
    op.add_column('patrimonio', sa.Column('frequencia_manutencao_meses', sa.Integer(), nullable=True))
    op.add_column('patrimonio', sa.Column('data_ultima_manutencao', sa.Date(), nullable=True))
    op.add_column('patrimonio', sa.Column('data_proxima_manutencao', sa.Date(), nullable=True))
    op.add_column('patrimonio', sa.Column('observacao_manutencao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patrimonio', 'observacao_manutencao')
    op.drop_column('patrimonio', 'data_proxima_manutencao')
    op.drop_column('patrimonio', 'data_ultima_manutencao')
    op.drop_column('patrimonio', 'frequencia_manutencao_meses')
    op.drop_index(op.f('ix_manutencao_patrimonio_patrimonio_id'), table_name='manutencao_patrimonio')
    op.drop_table('manutencao_patrimonio')
    # ### end Alembic commands ###
