"""faixa bonificacao qualidade leite

Revision ID: b128c3e68913
Revises: 00c885d4b5bd
Create Date: 2026-07-20 12:03:24.235783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b128c3e68913'
down_revision: Union[str, Sequence[str], None] = '00c885d4b5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faixa_bonificacao_qualidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_min', sa.Float(), nullable=True),
    sa.Column('valor_max', sa.Float(), nullable=True),
    sa.Column('ajuste_por_litro', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faixa_bonificacao_qualidade_indicador'), 'faixa_bonificacao_qualidade', ['indicador'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faixa_bonificacao_qualidade_indicador'), table_name='faixa_bonificacao_qualidade')
    op.drop_table('faixa_bonificacao_qualidade')
    # ### end Alembic commands ###
