"""backup automatico

Revision ID: b38274335d19
Revises: 4fd5c3d0e62d
Create Date: 2026-07-19 19:58:53.850652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b38274335d19'
down_revision: Union[str, Sequence[str], None] = '4fd5c3d0e62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_automatico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executado_em', sa.DateTime(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('erro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_automatico')
    # ### end Alembic commands ###
