"""
Camada de dados — modelos SQLModel (tabelas SQLite/PostgreSQL + validação Pydantic).
Cada modelo representa uma entidade do domínio da fazenda.

Este pacote foi dividido em submódulos por domínio (ver arquivos abaixo) para
facilitar a navegação — este __init__.py é só um shim de re-export: importa
todas as classes de todos os submódulos para que `from fazenda.models import X`
continue funcionando exatamente como antes da divisão, e para garantir que
todas as tabelas fiquem registradas no SQLModel.metadata/registry antes de
qualquer query (import eager de todos os submódulos).

NOTA: Relacionamentos usam strings forward-reference para compatibilidade
com SQLModel 0.0.39 + SQLAlchemy 2.x (sem Mapped[] em modelos com table=True).
"""
from __future__ import annotations

from sqlmodel import SQLModel

from .animais import (
    Animal,
    Lote,
    MovimentoLote,
    MotivoBaixa,
    MotivoVenda,
    Raca,
    GrauSangue,
    MotivoMovimentacao,
    ParametroSugestaoMovimentacao,
    BaixaAnimal,
    CompraAnimal,
    VendaAnimal,
    ComissaoCorretagem,
)
from .reprodutivo import (
    Servico,
    TipoServicoReprodutivo,
    MetodoServicoReprodutivo,
    ProtocoloIatfLancamento,
    ProtocoloIatfAplicacao,
    ProtocoloIatfHormonio,
    Parto,
    ColostragemBezerra,
)
from .producao import (
    ControleLeiteiro,
    PesagemCorporal,
    AgendamentoPesagem,
    QualidadeLeite,
    EntregaLeiteMensal,
    Secagem,
    FaixaBonificacaoQualidade,
)
from .financeiro import (
    ContaGerencial,
    LancamentoItem,
    LancamentoAnexo,
    PlanoContaGerencial,
    ContaCorrente,
    CentroCusto,
    TipoDocumento,
    FormaPagamentoCadastro,
    OrcamentoItem,
    PlanejamentoCenario,
    PlanejamentoItem,
    Pedido,
    PedidoItem,
    Patrimonio,
    ManutencaoPatrimonio,
    CurvaABC,
)
from .estoque import (
    Estoque,
    Fornecedor,
    MovimentoEstoque,
    EstoqueSemen,
    CompraSemen,
)
from .agricultura import (
    Safra,
)
from .pessoal import (
    TipoPessoa,
    Pessoa,
    FolhaPagamento,
    FeriasFuncionario,
    DecimoTerceiro,
    ValeFuncionario,
    ValeParcela,
    ValeAvulso,
    ValeAvulsoAbatimento,
    Empreitada,
    EmpreitadaParcela,
    EmpreitadaEtapa,
    Contrato,
    ContratoParcela,
    Diaria,
    DiariaPagamento,
    DiariaAuditoria,
    ParametroDiariaPadrao,
)
from .sanidade import (
    Sanidade,
    AplicacaoAgendada,
    PrincipioAtivo,
    MedicamentoComercial,
    Doenca,
    ExameDefinicao,
    ExameResultado,
    EventoSanitario,
    CalendarioSanitario,
    ServicoCadastro,
    ProtocoloSanitario,
    ProtocoloSanitarioEtapa,
    ProtocoloSanitarioLancamento,
    ProtocoloSanitarioAplicacao,
    ProtocoloInducaoLactacao,
    ProtocoloInducaoLactacaoEtapa,
    ProtocoloInducaoLancamento,
    ProtocoloInducaoMedicamento,
    ProtocoloInducaoAplicacao,
    Touro,
)
from .alimentacao import (
    CategoriaAlimento,
    Alimento,
    Dieta,
    DietaLancamento,
    DietaItemProgramado,
    IngredienteMS,
    TabelaNutricionalProduto,
    TabelaNutricionalValor,
    AnaliseBromatologica,
    DietaRegistroReal,
    AlimentacaoEstado,
)
from .recria import (
    OcorrenciaClinica,
    MetaRecria,
    PesoAlvoIdade,
    FaseRecria,
    JanelaPontoCritico,
    BenchmarkRecria,
    RegistroCocho,
    CategoriaManejo,
)
from .multitenant import (
    Fazenda,
    UsuarioFazenda,
    EmpresaOperadora,
)
from .planos import (
    PrecoModulo,
    ContratoFazenda,
    ContratoFazendaModulo,
    ContratoAnexo,
    ContratoAssinaturaZapSign,
)
from .cobranca import (
    CobrancaBoleto,
    CobrancaPix,
    CobrancaAsaas,
)
from .cowdata_interno import (
    LancamentoCowData,
)
from .cofre_acesso import (
    PedidoAcessoSuporte,
    SessaoAcessoSuporte,
    AuditoriaAcessoSuporte,
)
from .consultores import (
    ContratoConsultor,
    FazendaGerenciada,
    RegistroImportado,
)
from .sistema import (
    SeedFlag,
    ParametroFazenda,
    TelegramPendente,
    TelegramSessao,
    LancamentoPendente,
    AgendaManual,
    EventoRealizado,
    SolicitacaoExclusao,
    Usuario,
    LoginAcesso,
    BackupAutomatico,
    FonteNews,
    NoticiaNews,
    NotaCapa,
    PushSubscription,
    PushNotificacaoEnviada,
    PortalMensagem,
    ParametroManualFazenda,
    SugestaoManualFazenda,
)

__all__ = [
    "Fazenda",
    "UsuarioFazenda",
    "EmpresaOperadora",
    "PrecoModulo",
    "ContratoFazenda",
    "ContratoFazendaModulo",
    "ContratoAnexo",
    "ContratoAssinaturaZapSign",
    "CobrancaBoleto",
    "CobrancaPix",
    "ContratoConsultor",
    "FazendaGerenciada",
    "RegistroImportado",
    "Animal",
    "Lote",
    "MovimentoLote",
    "MotivoBaixa",
    "MotivoVenda",
    "Raca",
    "GrauSangue",
    "MotivoMovimentacao",
    "ParametroSugestaoMovimentacao",
    "BaixaAnimal",
    "CompraAnimal",
    "VendaAnimal",
    "ComissaoCorretagem",
    "Servico",
    "TipoServicoReprodutivo",
    "MetodoServicoReprodutivo",
    "ProtocoloIatfLancamento",
    "ProtocoloIatfAplicacao",
    "ProtocoloIatfHormonio",
    "Parto",
    "ColostragemBezerra",
    "ControleLeiteiro",
    "PesagemCorporal",
    "AgendamentoPesagem",
    "QualidadeLeite",
    "EntregaLeiteMensal",
    "Secagem",
    "FaixaBonificacaoQualidade",
    "ContaGerencial",
    "LancamentoItem",
    "LancamentoAnexo",
    "PlanoContaGerencial",
    "ContaCorrente",
    "CentroCusto",
    "TipoDocumento",
    "FormaPagamentoCadastro",
    "OrcamentoItem",
    "PlanejamentoCenario",
    "PlanejamentoItem",
    "Pedido",
    "PedidoItem",
    "Patrimonio",
    "ManutencaoPatrimonio",
    "Safra",
    "CurvaABC",
    "Estoque",
    "Fornecedor",
    "MovimentoEstoque",
    "EstoqueSemen",
    "CompraSemen",
    "TipoPessoa",
    "Pessoa",
    "FolhaPagamento",
    "FeriasFuncionario",
    "DecimoTerceiro",
    "ValeFuncionario",
    "ValeParcela",
    "ValeAvulso",
    "Empreitada",
    "EmpreitadaParcela",
    "EmpreitadaEtapa",
    "Contrato",
    "ContratoParcela",
    "Diaria",
    "DiariaPagamento",
    "DiariaAuditoria",
    "ParametroDiariaPadrao",
    "Sanidade",
    "AplicacaoAgendada",
    "PrincipioAtivo",
    "MedicamentoComercial",
    "Doenca",
    "ExameDefinicao",
    "ExameResultado",
    "EventoSanitario",
    "CalendarioSanitario",
    "ServicoCadastro",
    "ProtocoloSanitario",
    "ProtocoloSanitarioEtapa",
    "ProtocoloSanitarioLancamento",
    "ProtocoloSanitarioAplicacao",
    "ProtocoloInducaoLactacao",
    "ProtocoloInducaoLactacaoEtapa",
    "ProtocoloInducaoLancamento",
    "ProtocoloInducaoMedicamento",
    "ProtocoloInducaoAplicacao",
    "Touro",
    "CategoriaAlimento",
    "Alimento",
    "Dieta",
    "DietaLancamento",
    "DietaItemProgramado",
    "IngredienteMS",
    "TabelaNutricionalProduto",
    "TabelaNutricionalValor",
    "AnaliseBromatologica",
    "DietaRegistroReal",
    "AlimentacaoEstado",
    "OcorrenciaClinica",
    "MetaRecria",
    "PesoAlvoIdade",
    "FaseRecria",
    "JanelaPontoCritico",
    "BenchmarkRecria",
    "RegistroCocho",
    "CategoriaManejo",
    "SeedFlag",
    "ParametroFazenda",
    "TelegramPendente",
    "TelegramSessao",
    "LancamentoPendente",
    "AgendaManual",
    "EventoRealizado",
    "SolicitacaoExclusao",
    "Usuario",
    "LoginAcesso",
    "BackupAutomatico",
    "FonteNews",
    "NoticiaNews",
    "NotaCapa",
    "PushSubscription",
    "PushNotificacaoEnviada",
    "PortalMensagem",
    "ParametroManualFazenda",
    "SugestaoManualFazenda",
]
